config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "videos#index"
  resources :videos, only: [:index, :new, :create]
  resources :votes, only: [:index] do
    post :up_vote, on: :member, defaults: { format: :js }
    post :down_vote, on: :member, defaults: { format: :js }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :videos
  has_many :votes
  has_many :up_votes, -> { where(type_vote: :up_vote) }, class_name: "Vote"
  has_many :down_votes, -> { where(type_vote: :down_vote) }, class_name: "Vote"
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user
  has_many :votes
  has_many :up_votes, -> { where(type_vote: :up_vote) }, class_name: "Vote"
  has_many :down_votes, -> { where(type_vote: :down_vote) }, class_name: "Vote"

  delegate :email, to: :user, prefix: true

  validates :url, presence: true, uniqueness: true
  validate :valid_url?

  VideoInfo.provider_api_keys = { youtube: ENV['YOUTUBE_API_KEY'] }

  def valid_url?
    return if url.blank? || VideoInfo.valid_url?(url)

    errors.add(:base, "Please enter the correct youtube link")
  end

  def video_info
    VideoInfo.new(url)
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :video

  enum type_vote: { up_vote: 1, down_vote: 2 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]

  def index
    @videos = Video.order(created_at: :desc)
    if user_signed_in?
      @video_up_vote_ids = current_user.up_votes.pluck(:video_id)
      @video_down_vote_ids = current_user.down_votes.pluck(:video_id)
    end
  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(video_params)
    if @video.save
      flash[:success] = "Share success"
      redirect_to root_url
    else
      flash.now[:error] = @video.errors.full_messages
      render :new
    end
  end

  private

  def video_params
    params.require(:video).permit(:url).merge(user_id: current_user.id)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_video

  def up_vote
    if @vote.persisted? && @vote.type_vote == "up_vote"
      @vote.destroy
    else
      @vote.type_vote = :up_vote
      @vote.save
    end
    find_vote_number
    respond_to do |format|
      format.js
    end
  end

  def down_vote
    if @vote.persisted? && @vote.type_vote == "down_vote"
      @vote.destroy
    else
      @vote.type_vote = :down_vote
      @vote.save
    end
    find_vote_number
    respond_to do |format|
      format.js
    end
  end

  private

  def find_video
    @video = Video.find_by(id: params[:id])
    @vote = Vote.find_or_initialize_by(user_id: current_user.id, video_id: params[:id])
  end

  def find_vote_number
    @video_up_vote_ids = current_user.up_votes.pluck(:video_id)
    @video_down_vote_ids = current_user.down_votes.pluck(:video_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class flash_type
    case flash_type.to_sym
    when :success
      'bg-green-100 border-green-400 text-green-700'
    when :error
      'bg-red-100 border-red-400 text-red-700'
    else
      flash_type.to_s
    end
  end

  def error_list messages
    content_tag :ul do
      messages.map {|item| content_tag(:li, item) }.join.html_safe
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShareYoutube</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto px-5 mt-6">
      <div class="grid grid-cols-3 mb-5 border-b">
        <div class="col-span-1 text-center">
          <%= link_to root_url, class: "flex" do %>
            <%= fa_icon "4x home"%>
            <div style="line-height: 4rem" class="text-3xl">Funny Movie</div>
          <% end %>
        </div>
        <div class="col-span-2 text-right">
          <% if user_signed_in? %>
            <%= current_user.email %>
            <%= link_to "Share a movie", new_video_path, class: "mt-5 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "mt-5 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
        <% else %>
            <%= link_to "Login", new_user_session_path, class: "mt-5 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
            <%= link_to "Signin", new_user_registration_path, class: "mt-5 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
          <% end %>
        </div>
      </div>
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, messages| %>
  <div class="<%= flash_class(type) %> border px-4 py-3 rounded relative mb-5" role="alert">
    <% if messages.is_a? Array %>
      <%= (messages.length > 1) ? error_list(messages) : messages.first %>
    <% elsif messages.is_a? Hash %>
      <ul>
        <% messages.each do |i, line_messages| %>
          <li><%= t 'commons.line_number', line: i %></li>
          <%= error_list line_messages %>
        <% end %>
      </ul>
    <% else %>
      <%= messages %>
    <% end %>
  </div>
<% end %>

app/views/videos/_down_vote.html.erb
<%= button_to down_vote_vote_path(video.id), remote: true, method: :post do %>
  <% if @video_down_vote_ids.include?(video.id) %>
    <%= fa_icon "thumbs-down lg", class: "ms-2 me-4" %>
  <% else %>
    <%= fa_icon "thumbs-o-down lg", class: "ms-2 me-4" %>
  <% end %>
<% end %>

app/views/videos/_up_vote.html.erb
<%= button_to up_vote_vote_path(video.id), remote: true, method: :post do %>
  <% if @video_up_vote_ids.include?(video.id) %>
    <%= fa_icon "thumbs-up lg", class: "ms-2 me-4" %>
  <% else %>
    <%= fa_icon "thumbs-o-up lg", class: "ms-2 me-4" %>
  <% end %>
<% end %>

app/views/videos/_video.html.erb
<% video_info = video.video_info %>
<div class="lg:col-span-4 md:col-span-8 mb-5">
  <iframe
    width="560"
    height="315"
    src="https://www.youtube.com/embed/<%= video_info.video_id %>"
    title="YouTube video player"
    frameborder="0"
    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
    allowfullscreen>
  </iframe>
</div>
<div class="lg:col-span-4 md:col-span-8 mb-5">
  <div class="font-bold text-lg my-2 text-red-700"><%= video_info.title %></div>
  <div class="text-base my-2">Shared by: <%= video.user_email %></div>
  <% if user_signed_in? %>
    <div class="vote-<%= video.id %> flex">
     <%= render "vote", video: video %>
    </div>
  <% end %>
  <div class="text-base my-2">Description:</div>
  <div class="text-sm my-2"><%= raw video_info.description %></div>
</div>

app/views/videos/_vote.html.erb
<%= video.up_votes.size %>
<%= render "videos/up_vote", video: video %>
<%= video.down_votes.size %>
<%= render "videos/down_vote", video: video %>

app/views/videos/index.html.erb
<%= render "shared/flash_messages" %>
<div class="grid grid-cols-8 mx-20">
  <%=  render @videos %>
</div>

app/views/videos/new.html.erb
<%= render "shared/flash_messages" %>
<div class="grid grid-cols-6 gap-4">
  <div class="col-start-2 col-span-4">
    Share a youtube movie

    <div class="box-border p-4 border-4">
      <%= form_for @video, method: :post do |f| %>
        <div class="grid grid-cols-5">
          <div class="col-span-1">
            <%= f.label :url %>
          </div>
          <div class="col-span-4">
            <%= f.url_field :url, autofocus: true, class: "w-full"%>
          </div>
          <div class="col-span-1">
          </div>
          <div class="col-span-4">
            <%= f.submit "Share", class: "mt-5 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/votes/down_vote.js.erb
$('.vote-<%= @video.id %>').html('<%= j render("videos/vote", video: @video) %>');

app/views/votes/up_vote.js.erb
$('.vote-<%= @video.id %>').html('<%= j render("videos/vote", video: @video) %>');